language: python
python:
  - '3.7'

services:
  - postgresql
addons:
  postgresql: "12"
  apt:
    packages:
    - postgresql-12
    - postgresql-client-12

before_install:
# setting up postgres 12 is quite a pain, see:
# https://travis-ci.community/t/test-against-postgres-12/6768/8
  - sudo cp /etc/postgresql/10/main/pg_hba.conf /etc/postgresql/12/main/pg_hba.conf
  - sudo pg_ctlcluster 12 main restart
  - sh -c 'until pg_isready -p 5433; do echo "Waiting for the DB to be up..."; sleep 2; done'
  - psql -U postgres -p 5433 -c "CREATE USER testuser WITH PASSWORD 'secret' LOGIN;"
  - psql -U postgres -p 5433 -c "CREATE DATABASE grammarquiz OWNER testuser;"
  - psql -U testuser -p 5433 -f scripts/populate_db/schema.sql grammarquiz
  - psql -U testuser -p 5433 -q -f tests/database_content.sql grammarquiz
# manually install nodejs 12, the one provided for some reason is 8.x
  - curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
  - sudo apt-get update
  - sudo apt-get install -y nodejs
  - nvm ls
  - nvm use latest
env:
  global:
  - PG_CONN_STR="postgresql://testuser:secret@localhost:5433/grammarquiz"
  - SSO_GOOGLE_CLIENT_ID="fake"
  - SSO_GOOGLE_SECRET="fake"
  - SECRET_SESSION_KEY="fake"

install:
  - make local-install
script: make test-all
