language: python
python:
  - '3.7'
node_js:
  - 12
services:
  - postgresql

addons:
  postgresql: "12"
  apt:
    packages:
    - postgresql-12
    - postgresql-client-12

before_script:
  - psql -U postgres -c "CREATE USER testuser WITH PASSWORD 'secret' LOGIN;"
  - psql -U postgres -c "CREATE DATABASE grammarquiz OWNER testuser;"
  - psql -U testuser -f scripts/populate_db/schema.sql grammarquiz
  - psql -U testuser -q -f tests/database_content.sql grammarquiz

env:
  global:
  - PGPORT=5433
  - PG_CONN_STR="postgresql://testuser:secret@localhost:5433/grammarquiz"
  - SSO_GOOGLE_CLIENT_ID="fake"
  - SSO_GOOGLE_SECRET="fake"
  - SECRET_SESSION_KEY="fake"

install:
  - make local-install
script: make test-all
