language: python
python:
  - '3.7'
node_js:
  - 12
services:
  - postgresql

before_script:
  - psql -c "CREATE DATABASE grammarquiz;" -U postgres
  - psql -c "CREATE USER foo WITH PASSWORD 'secret' LOGIN;" -U postgres
  - psql -U postgres -f scripts/populate_db/schema.sql grammarquiz
  - psql -U postgres -q -f tests/database_content.sql grammarquiz

env:
  - PG_CONN_STR="postgresql://foo:secret@localhost:5432/grammarquiz"

install:
  - make local-install
script: make test-all
