language: python
python:
  - '3.7'
node_js:
  - 12

addons:
  postgresql: "12"
  apt:
    packages:
    - postgresql-12
    - postgresql-client-12

before_install:
# See here:
# https://stackoverflow.com/questions/61734368/postgresql-12-on-travis-ci-taking-5-minutes-to-startup
  - sudo sed -i 's/port = 5433/port = 5432/' /etc/postgresql/12/main/postgresql.conf
  - sudo cp /etc/postgresql/{9.3,12}/main/pg_hba.conf
  - sudo pg_ctlcluster 12 main restart
  - psql -U postgres -c "CREATE USER testuser WITH PASSWORD 'secret' LOGIN;"
  - psql -U postgres -c "CREATE DATABASE grammarquiz OWNER testuser;"
  - psql -U testuser -f scripts/populate_db/schema.sql grammarquiz
  - psql -U testuser -q -f tests/database_content.sql grammarquiz

env:
  global:
  - PG_CONN_STR="postgresql://testuser:secret@localhost:5432/grammarquiz"
  - SSO_GOOGLE_CLIENT_ID="fake"
  - SSO_GOOGLE_SECRET="fake"
  - SECRET_SESSION_KEY="fake"

install:
  - make local-install
script: make test-all
