# extracted from https://github.com/RyckRichards/tatoeba2/blob/dev/src/Lib/LanguagesLib.php # NOQA
ISO_693_3 = {
    'ara': 'Arabic',
    'eng': 'English',
    'jpn': 'Japanese',
    'fra': 'French',
    'deu': 'German',
    'spa': 'Spanish',
    'ita': 'Italian',
    'vie': 'Vietnamese',
    'rus': 'Russian',
    'cmn': 'Mandarin Chinese',
    'kor': 'Korean',
    'nld': 'Dutch',
    'heb': 'Hebrew',
    'ind': 'Indonesian',
    'por': 'Portuguese',
    'fin': 'Finnish',
    'bul': 'Bulgarian',
    'ukr': 'Ukrainian',
    'ces': 'Czech',
    'epo': 'Esperanto',
    'ell': 'Greek',
    'tur': 'Turkish',
    'swe': 'Swedish',
    'nob': 'Norwegian Bokmål',
    'zsm': 'Malay',
    'est': 'Estonian',
    'kat': 'Georgian',
    'pol': 'Polish',
    'swh': 'Swahili',
    'lat': 'Latin',
    # TODO to change when shanghainese will not be the only wu dialect
    'wuu': 'Shanghainese',
    'arz': 'Egyptian Arabic',
    'bel': 'Belarusian',
    'hun': 'Hungarian',
    'isl': 'Icelandic',
    'sqi': 'Albanian',
    'yue': 'Cantonese',
    'afr': 'Afrikaans',
    'fao': 'Faroese',
    'fry': 'Frisian',
    'bre': 'Breton',
    'ron': 'Romanian',
    'uig': 'Uyghur',
    'uzb': 'Uzbek',
    'nno': 'Norwegian Nynorsk',
    'srp': 'Serbian',
    'tat': 'Tatar',
    'yid': 'Yiddish',
    'pes': 'Persian',
    'nan': 'Min Nan Chinese',
    'eus': 'Basque',
    'slk': 'Slovak',
    'dan': 'Danish',
    'hye': 'Armenian',
    'acm': 'Iraqi Arabic',
    'san': 'Sanskrit',
    'urd': 'Urdu',
    'hin': 'Hindi',
    'ben': 'Bengali',
    'cycl': 'CycL',
    'cat': 'Catalan',
    'kaz': 'Kazakh',
    'lvs': 'Latvian',
    'bos': 'Bosnian',
    'hrv': 'Croatian',
    'orv': 'Old East Slavic',
    'cha': 'Chamorro',
    'tgl': 'Tagalog',
    'que': 'Quechua',
    'mon': 'Mongolian',
    'lit': 'Lithuanian',
    'glg': 'Galician',
    'gle': 'Irish',
    'ina': 'Interlingua',
    'jbo': 'Lojban',
    'toki': 'Toki Pona',
    'ain': 'Ainu',
    'scn': 'Sicilian',
    'mal': 'Malayalam',
    'nds': 'Low German (Low Saxon)',
    'tlh': 'Klingon',
    'slv': 'Slovenian',
    'tha': 'Thai',
    'lzh': 'Literary Chinese',
    'oss': 'Ossetian',
    'roh': 'Romansh',
    'vol': 'Volapük',
    'gla': 'Scottish Gaelic',
    'ido': 'Ido',
    'ast': 'Asturian',
    'ile': 'Interlingue',
    'oci': 'Occitan',
    'xal': 'Kalmyk',
    'ang': 'Old English',
    'kur': 'Kurdish',
    'dsb': 'Lower Sorbian',
    'hsb': 'Upper Sorbian',
    'ksh': 'Kölsch',
    'cym': 'Welsh',
    'ewe': 'Ewe',
    'sjn': 'Sindarin',
    'tel': 'Telugu',
    'tpi': 'Tok Pisin',
    'qya': 'Quenya',
    'nov': 'Novial',
    'mri': 'Maori',
    'lld': 'Ladin',
    'ber': 'Berber',
    'xho': 'Xhosa',
    'pnb': 'Punjabi (Western)',
    'mlg': 'Malagasy',
    'grn': 'Guarani',
    'lad': 'Ladino',
    'pms': 'Piedmontese',
    'avk': 'Kotava',
    'mar': 'Marathi',
    'tpw': 'Old Tupi',
    'tgk': 'Tajik',
    'prg': 'Old Prussian',
    'npi': 'Nepali',
    'mlt': 'Maltese',
    'ckt': 'Chukchi',
    'cor': 'Cornish',
    'aze': 'Azerbaijani',
    'khm': 'Khmer',
    'lao': 'Lao',
    'bod': 'Tibetan',
    'hil': 'Hiligaynon',
    'arq': 'Algerian Arabic',
    'pcd': 'Picard',
    'grc': 'Ancient Greek',
    'amh': 'Amharic',
    'awa': 'Awadhi',
    'bho': 'Bhojpuri',
    'cbk': 'Chavacano',
    'enm': 'Middle English',
    'frm': 'Middle French',
    'hat': 'Haitian Creole',
    'jdt': 'Juhuri (Judeo-Tat)',
    'kal': 'Greenlandic',
    'mhr': 'Meadow Mari',
    'nah': 'Nahuatl',
    'pdc': 'Pennsylvania German',
    'sin': 'Sinhala',
    'tuk': 'Turkmen',
    'wln': 'Walloon',
    'bak': 'Bashkir',
    'hau': 'Hausa',
    'ltz': 'Luxembourgish',
    'mgm': 'Mambae',
    'som': 'Somali',
    'zul': 'Zulu',
    'haw': 'Hawaiian',
    'kir': 'Kyrgyz',
    'mkd': 'Macedonian',
    'mrj': 'Hill Mari',
    'ppl': 'Pipil',
    'yor': 'Yoruba',
    'kin': 'Kinyarwanda',
    'shs': 'Shuswap',
    'chv': 'Chuvash',
    'lkt': 'Lakota',
    'ota': 'Ottoman Turkish',
    'sna': 'Shona',
    'mnw': 'Mon',
    'nog': 'Nogai',
    'sah': 'Yakut',
    'abk': 'Abkhaz',
    'tet': 'Tetun',
    'tam': 'Tamil',
    'udm': 'Udmurt',
    'kum': 'Kumyk',
    'crh': 'Crimean Tatar',
    'nya': 'Chinyanja',
    'liv': 'Livonian',
    'nav': 'Navajo',
    'chr': 'Cherokee',
    'guj': 'Gujarati',
    'pan': 'Punjabi (Eastern)',
    'kha': 'Khasi',
    'jav': 'Javanese',
    'zza': 'Zaza',
    'egl': 'Emilian',
    'tir': 'Tigrinya',
    'sme': 'Northern Sami',
    'max': 'North Moluccan Malay',
    'pam': 'Kapampangan',
    'dtp': 'Central Dusun',
    'cho': 'Choctaw',
    'kzj': 'Coastal Kadazan',
    'smo': 'Samoan',
    'fij': 'Fijian',
    'wol': 'Wolof',
    'che': 'Chechen',
    'sag': 'Sango',
    'hif': 'Fiji Hindi',
    'ton': 'Tongan',
    'ngt': 'Ngeq ',
    'kam': 'Kamba',
    'vec': 'Venetian',
    'mya': 'Burmese',
    'gil': 'Gilbertese',
    'myv': 'Erzya',
    'niu': 'Niuean',
    'vro': 'Võro',
    'glv': 'Manx',
    'lin': 'Lingala',
    'lfn': 'Lingua Franca Nova',
    'pus': 'Pashto',
    'kjh': 'Khakas',
    'dng': 'Dungan',
    'fur': 'Friulian',
    'mah': 'Marshallese',
    'pfl': 'Palatine German',
    'kan': 'Kannada',
    'crs': 'Seychellois Creole',
    'gsw': 'Swiss German',
    'osx': 'Old Saxon',
    'sux': 'Sumerian',
    'sco': 'Scots',
    'moh': 'Mohawk',
    'ceb': 'Cebuano',
    'lmo': 'Lombard',
    'tso': 'Tsonga',
    'bua': 'Buryat',
    'aym': 'Aymara',
    'ilo': 'Ilocano',
    'kaa': 'Karakalpak',
    'nlv': 'Orizaba Nahuatl',
    'ngu': 'Guerrero Nahuatl',
    'ady': 'Adyghe',
    'brx': 'Bodo',
    'gag': 'Gagauz',
    'rom': 'Romani',
    'lzz': 'Laz',
    'fuc': 'Pulaar',
    'umb': 'Umbundu',
    'tkl': 'Tokelauan',
    'sot': 'Southern Sotho',
    'alt': 'Southern Altai',
    'war': 'Waray',
    'snd': 'Sindhi',
    'tsn': 'Setswana',
    'srd': 'Sardinian',
    'pau': 'Palauan',
    'gbm': 'Garhwali',
    'oji': 'Ojibwe',
    'lug': 'Luganda',
    'hak': 'Hakka Chinese',
    'bam': 'Bambara',
    'arg': 'Aragonese',
    'asm': 'Assamese',
    'fuv': 'Nigerian Fulfulde',
    'hoc': 'Ho',
    'sun': 'Sundanese',
    'apc': 'North Levantine Arabic',
    'tyv': 'Tuvinian',
    'krc': 'Karachay-Balkar',
    'pap': 'Papiamento',
    'non': 'Old Norse',
    'ori': 'Odia (Oriya)',
    'iba': 'Iban',
    'oar': 'Old Aramaic',
    'ary': 'Moroccan Arabic',
    'cyo': 'Cuyonon',
    'ibo': 'Igbo',
    'csb': 'Kashubian',
    'lou': 'Louisiana Creole',
    'urh': 'Urhobo',
    'mvv': 'Tagal Murut',
    'mdf': 'Moksha',
    'pag': 'Pangasinan',
    'cos': 'Corsican',
    'hnj': 'Hmong Njua (Green)',
    'rif': 'Tarifit',
    'nch': 'Central Huasteca Nahuatl',
    'kek': "Kekchi (Q'eqchi')",
    'ssw': 'Swazi',
    'ban': 'Balinese',
    'aii': 'Assyrian Neo-Aramaic',
    'tvl': 'Tuvaluan',
    'kxi': 'Keningau Murut',
    'bvy': 'Baybayanon',
    'mfe': 'Morisyen',
    'mww': 'Hmong Daw (White)',
    'bcl': 'Central Bikol',
    'nau': 'Nauruan',
    'zlm': 'Malay (Vernacular)',
    'nst': 'Naga (Tangshang)',
    'quc': "K'iche'",
    'afb': 'Gulf Arabic',
    'min': 'Minangkabau',
    'tmw': 'Temuan',
    'cjy': 'Jin Chinese',
    'mai': 'Maithili',
    'mad': 'Madurese',
    'bjn': 'Banjar',
    'got': 'Gothic',
    'hsn': 'Xiang Chinese',
    'gan': 'Gan Chinese',
    'bar': 'Bavarian',
    'tzl': 'Talossan',
    'sgs': 'Samogitian',
    'ldn': 'Láadan',
    'dws': 'Dutton World Speedwords',
    'afh': 'Afrihili',
    'krl': 'Karelian',
    'vep': 'Veps',
    'rue': 'Rusyn',
    'tah': 'Tahitian',
    'tly': 'Talysh',
    'mic': "Mi'kmaq",
    'ext': 'Extremaduran',
    'swg': 'Swabian',
    'izh': 'Ingrian',
    'sma': 'Southern Sami',
    'jam': 'Jamaican Patois',
    'mwl': 'Mirandese',
    'kpv': 'Komi-Zyrian',
    'cmo': 'Central Mnong',
    'koi': 'Komi-Permyak',
    'ike': 'Inuktitut',
    'kab': 'Kabyle',
    'run': 'Kirundi',
    'aln': 'Gheg Albanian',
    'akl': 'Aklanon',
    'mnc': 'Manchu',
    'kas': 'Kashmiri',
    'otk': 'Old Turkish',
    'aoz': 'Uab Meto',
    'shy': 'Tachawit',
    'fkv': 'Kven Finnish',
    'rap': 'Rapa Nui',
    'gcf': 'Guadeloupean Creole French',
    'gos': 'Gronings',
    'lij': 'Ligurian',
    'tig': 'Tigre',
    'thv': 'Tahaggart Tamahaq',
    'div': 'Dhivehi',
    'hrx': 'Hunsrik',
    'cay': 'Cayuga',
    'gaa': 'Ga',
    'cpi': 'Chinese Pidgin English',
    'bzt': 'Brithenig',
    'ltg': 'Latgalian',
    'emx': 'Erromintxela',
    'gom': 'Konkani (Goan)',
    'chg': 'Chagatai',
    'xmf': 'Mingrelian',
    'osp': 'Old Spanish',
    'tmr': 'Jewish Babylonian Aramaic',
    'ryu': 'Okinawan',
    'evn': 'Evenki',
    'bis': 'Bislama',
    'stq': 'Saterland Frisian',
    'fro': 'Old French',
    'syc': 'Syriac',
    'frr': 'North Frisian',
    'nys': 'Nyungar',
    'tts': 'Isan',
    'toi': 'Tonga (Zambezi)',
    'new': 'Newari',
    'jpa': 'Jewish Palestinian Aramaic',
    'phn': 'Phoenician',
    'rel': 'Rendille',
}
